apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db-username: dXNlcm5hbWU=  # base64 encoded value for "username"
  db-password: cGFzc3dvcmQ=  # base64 encoded value for "password"
